[package]
name = "compiler"
version = "0.1.0"
edition = "2018"

[build-dependencies]
lalrpop = "0.20.0"

[dependencies]
lazy_static = "1.4.0"
lalrpop-util = { version = "0.20.0", features = ["lexer"] }
koopa = "0.0.7"
